maintainer       "Outbrain, Inc."
maintainer_email "nathan@outbrain.com"
license          "All rights reserved"
description      "Installs/Configures hadoop"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.1.0"
recipe           "ob-hadoop-test::default", "Installs hadoop base libraries and conguration."
recipe           "ob-hadoop-test::hive", "Installs the Hive CLI and configuration."
recipe           "ob-hadoop-test::hivemetastore", "Installs mysql-instance prepped to become a hive metastore."
recipe           "ob-hadoop-test::hive-thrift", "Installs the init ifrasructure to run a hive-thrift server insance."
recipe           "ob-hadoop-test::jobtracker", "Installs the JobTracker package and prepares the file system."
recipe           "ob-hadoop-test::namenode", "Installs the NameNode package and prepares the file system."
recipe           "ob-hadoop-test::secondarynamenode", "Installs the SecondaryNameNode package and prepares the file system."
recipe           "ob-hadoop-test::slave", "Installs the DataNode and TaskTracker packages and prepares the file system."
