maintainer       "Outbrain, Inc."
maintainer_email "nathan@outbrain.com"
license          "All rights reserved"
description      "Installs/Configures hadoop"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.1.1"
recipe           "hadoop::default", "Installs hadoop base libraries and conguration."
recipe           "hadoop::hive", "Installs the Hive CLI and configuration."
recipe           "hadoop::hivemetastore", "Installs mysql-instance prepped to become a hive metastore."
recipe           "hadoop::hive-thrift", "Installs the init ifrasructure to run a hive-thrift server insance."
recipe           "hadoop::jobtracker", "Installs the JobTracker package and prepares the file system."
recipe           "hadoop::namenode", "Installs the NameNode package and prepares the file system."
recipe           "hadoop::secondarynamenode", "Installs the SecondaryNameNode package and prepares the file system."
recipe           "hadoop::slave", "Installs the DataNode and TaskTracker packages and prepares the file system."
